name: Static Website CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          npm install -g htmlhint stylelint stylelint-config-standard lighthouse

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1.7.1

      - name: Install LinkChecker
        run: sudo apt-get install linkchecker

      - name: Install http-server
        run: sudo npm install -g http-server
        continue-on-error: true

      - name: Validate HTML
        run: htmlhint '**/*.html'
        continue-on-error: true

      - name: Lint CSS
        run: |
          echo "module.exports = { extends: 'stylelint-config-standard' };" > .stylelintrc.js
          stylelint '**/*.css'
        continue-on-error: true

      - name: Check for broken links
        run: linkchecker ./index.html
        continue-on-error: true

      - name: Start local server
        run: |
          http-server -p 8080 &
          sleep 5 # wait for server to start

      - name: Find Chromium Path
        run: |
          CHROMIUM_PATH=$(find / -type f -name "chromium-browser" 2>/dev/null | head -n 1)
          echo "Chromium found at: $CHROMIUM_PATH"

      - name: Check if Local Server is Running
        run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080)
          if [ $response -eq 200 ]; then
            echo "Local server is running and accessible."
          else
            echo "Local server is not running or not accessible. Response code: $response"
            exit 1
          fi

      # Not working yet:
      # - name: Run accessibility tests (Lighthouse)
      #   run: lighthouse http://localhost:8080 --output json --output html --output-path ./lighthouse --chrome-path CHROMIUM_PATH
